module.exports = Object.freeze({
	ROW: 'Row',
	RANK: 'Rank',
    SOURCE_TABLE: 'SourceTable',
	SOURCE_COLUMN: 'SourceColumn',
	DEST_COLUMN: 'DestinationColumn',
	DEST_TABLE: 'DestinationTable',
	DEST_VALUE: 'DestinationValue',
	JOIN_TABLE_COLUMN: 'JoinTable',
	CONDITIONS: 'Conditions',
	SELECT: 'SELECT',
	PK_ALIAS: 'ID',
	TRID_ALIAS: 'TRID',
	INSERT_COL_ID: 'id',
	INSERT_COL_TRID: 'transaction_id',
	INSERT_COL_REL_NAME: 'name_',
	NAME_ALIAS: 'NME',
	SRC_TBL_PFX: 's$',
    DEST_TBL_PFX: 't$',
    RELTBLPFXS: ['s$','t$']
});